/* Slots Regions must be aligned on 2048 bytes (0x800) */

/* swap region (44 kbytes) */
__ICFEDIT_region_SWAP_start__   = 0x081D5000;
__ICFEDIT_region_SWAP_end__     = 0x081DFFFF;

/* slot 0 region (748 kbytes) */
__ICFEDIT_region_SLOT_0_start__ = 0x08105000;
__ICFEDIT_region_SLOT_0_end__   = 0x081BFFFF;

/* slot 1 region (748 kbytes) */
__ICFEDIT_region_SLOT_1_start__ = 0x08036000;
__ICFEDIT_region_SLOT_1_end__   = 0x080F0FFF;

